/** UKF spec version supported. */
export const UKF_VERSION = '025';

/** Section code labels per UKF specification. */
export const SECTION_LABELS: Record<string, string> = {
  '411': 'Dauermedikation',
  '412': 'Bedarfsmedikation',
  '413': 'Infusionstherapie',
  '414': 'Parenterale Ernährung',
  '415': 'Besondere Zubereitungen',
  '416': 'Neue Medikation',
  '417': 'Geänderte Medikation',
  '418': 'Abgesetzte Medikation',
  '419': 'Medikation bei Entlassung',
  '421': 'Selbstmedikation',
  '422': 'Sonstige Hinweise',
};

/** Dosage form codes per UKF specification. */
export const DOSAGE_FORM_LABELS: Record<string, string> = {
  AEO: 'Ätherisches Öl',
  AMP: 'Ampullen',
  APA: 'Augenpaste',
  ASN: 'Augenspülflüssigkeit',
  ASO: 'Augenspüllösung',
  ATO: 'Augentropfen',
  AUB: 'Augenbad',
  AUC: 'Augencreme',
  AUG: 'Augengel',
  AUS: 'Augensalbe',
  BAD: 'Bad',
  BAL: 'Balsam',
  BAN: 'Bandage',
  BEU: 'Beutel',
  BIN: 'Binden',
  BON: 'Bonbons',
  BPL: 'Basisplatte',
  BRE: 'Brei',
  BTA: 'Brausetabletten',
  CRE: 'Creme',
  DFL: 'Durchstechflaschen',
  DIG: 'Digitale Gesundheitsanwendungen',
  DIL: 'Dilution',
  DKA: 'Dragees in Kalenderpackung',
  DRA: 'Dragees',
  DRM: 'Dragees magensaftresistent',
  DSC: 'Dosierschaum',
  DSS: 'Dosierspray',
  EDP: 'Einzeldosis-Pipetten',
  EIN: 'Einreibung',
  ELE: 'Elektroden',
  ELI: 'Elixier',
  EMU: 'Emulsion',
  ESS: 'Essenz',
  ESU: 'Erwachsenen-Suppositorien',
  EXT: 'Extrakt',
  FBE: 'Filterbeutel',
  FBW: 'Franzbranntwein',
  FDA: 'Filmdragees',
  FER: 'Fertigspritzen',
  FET: 'Fettsalbe',
  FLA: 'Flasche',
  FLE: 'Flüssigkeit zum Einnehmen',
  FLU: 'Flüssig',
  FMR: 'Filmtabletten magensaftresistent',
  FOL: 'Folie',
  FRB: 'Beutel mit retardierten Filmtabletten',
  FSE: 'Flüssigseife',
  FTA: 'Filmtabletten',
  GEK: 'Granulat zur Entnahme aus Kapseln',
  GEL: 'Gel',
  GLI: 'Gas und Lösungsmittel zur Herstellung einer Injektions-/Infusionsdispersion',
  GLO: 'Globuli',
  GPA: 'Gel-Pflaster',
  GRA: 'Granulat',
  GSE: 'Granulat zur Herstellung einer Suspension zum Einnehmen',
  GUL: 'Gurgellösung',
  HAS: 'Handschuhe',
  HKM: 'Hartkapseln mit magensaftresistenter Wirkstofffreisetzung',
  HKP: 'Hartkapseln',
  HPI: 'Hartkapseln mit Pulver zur Inhalation',
  HVW: 'Hartkapseln mit veränderter Wirkstofffreisetzung',
  IFA: 'Infusionsampullen',
  IFB: 'Infusionsbeutel',
  IFD: 'Infusionsdispersion',
  IFE: 'Injektionslösung in einer Fertigspritze',
  IFF: 'Infusionsflaschen',
  IFK: 'Infusionslösungskonzentrat',
  IFL: 'Injektionsflaschen',
  IFS: 'Infusionsset',
  IHA: 'Inhalationsampullen',
  IHP: 'Inhalationspulver',
  IIE: 'Injektions- oder Infusionslösung oder Lösung zum Einnehmen',
  IIL: 'Injektions-, Infusionslösung',
  IJD: 'Injektionsdispersion',
  IKA: 'Inhalationskapseln',
  ILO: 'Injektionslösung',
  IMP: 'Implantat',
  INF: 'Infusionslösung',
  INH: 'Inhalat',
  INI: 'Injektions-/Infusionsflaschen',
  INL: 'Inhalationslösung',
  INS: 'Instillation',
  IST: 'Injektionssuspension',
  ISU: 'Injektions-/Infusionssuspension',
  IUP: 'Intrauterinpessar',
  KAN: 'Kanülen',
  KAP: 'Kapseln',
  KAT: 'Katheter',
  KDA: 'Kaudragees',
  KEG: 'Kegel',
  KER: 'Kerzen',
  KGU: 'Kaugummi',
  KID: 'Konzentrat zur Herstellung einer Infusionsdispersion',
  KII: 'Konzentrat zur Herstellung einer Injektions- oder Infusionslösung',
  KKS: 'Kleinkinder-Suppositorien',
  KLI: 'Klistiere',
  KLT: 'Klistier-Tabletten',
  KMP: 'Hartkapseln mit Magensaftresistenten Pellets',
  KMR: 'Kapseln magensaftresistent',
  KOD: 'Kondome',
  KOM: 'Kompressen',
  KON: 'Konzentrat',
  KPG: 'Kombipackung',
  KSS: 'Kinder- und Säuglings-Suppositorien',
  KSU: 'Kinder-Suppositorien',
  KTA: 'Kautabletten',
  LAN: 'Lanzetten',
  LII: 'Lösung zur Injektion, Infusion und Inhalation',
  LIN: 'Liniment',
  LIQ: 'Liquidum',
  LOE: 'Lösung',
  LOT: 'Lotion',
  LOV: 'Lösung für einen Vernebler',
  LSE: 'Lösung zum Einnehmen',
  LTA: 'Lacktabletten',
  LUP: 'Lutschpastillen',
  LUT: 'Lutschtabletten',
  MIL: 'Milch',
  MIS: 'Mischung',
  MIX: 'Mixtur',
  MRG: 'Magensaftresistentes Granulat',
  MRP: 'Magensaftresistente Pellets',
  MTA: 'Manteltabletten',
  MUW: 'Mundwasser',
  NAG: 'Nasengel',
  NAO: 'Nasenöl',
  NAS: 'Nasenspray',
  NAW: 'Wirkstoffhaltiger Nagellack',
  NDS: 'Nasendosierspray',
  NSA: 'Nasensalbe',
  NTR: 'Nasentropfen',
  OCU: 'Ocusert',
  OEL: 'Öl',
  OHT: 'Ohrentropfen',
  OVU: 'Ovula',
  PAM: 'Packungsmasse',
  PAS: 'Paste',
  PEL: 'Pellets',
  PEN: 'Injektionslösung in einem Fertigpen',
  PER: 'Perlen',
  PFL: 'Pflaster',
  PFT: 'Pflaster transdermal',
  PHI: 'Pulver zur Herstellung einer Infusionslösung',
  PHV: 'Pulver zur Herstellung einer Injektions- oder Infusionslösung oder Lösung zum Einnehmen',
  PIE: 'Pulver für ein Konzentrat zur Herstellung einer Infusionslösung',
  PIF: 'Pulver zur Herstellung einer Infusionssuspension',
  PII: 'Pulver zur Herstellung einer Injektions- bzw. Infusionslösung',
  PIJ: 'Pulver zur Herstellung einer Injektionslösung',
  PIK: 'Pulver zur Herstellung eines Infusionslösungskonzentrates',
  PIS: 'Pulver zur Herstellung einer Injektionssuspension',
  PIV: 'Pulver zur Herstellung einer Injektions-/Infusionslösung oder einer Lösung zur intravesikalen Anwendung',
  PKI: 'Pulver für ein Konzentrat zur Herstellung einer Infusionslösung',
  PLE: 'Pulver zur Herstellung einer Lösung zum Einnehmen',
  PLF: 'Pulver und Lösungsmittel zur Herstellung einer Infusionslösung',
  PLG: 'Perlongetten',
  PLH: 'Pulver und Lösungsmittel zur Herstellung einer Injektions- bzw. Infusionslösung',
  PLI: 'Pulver und Lösungsmittel zur Herstellung einer Injektionslösung',
  PLK: 'Pulver und Lösungsmittel für ein Konzentrat zur Herstellung einer Infusionslösung',
  PLS: 'Pulver und Lösungsmittel zur Herstellung einer Injektionssuspension',
  PLV: 'Pulver',
  PPL: 'Pumplösung',
  PRS: 'Presslinge',
  PSE: 'Pulver zur Herstellung einer Suspension zum Einnehmen',
  PST: 'Paste',
  PUD: 'Puder',
  PUL: 'Pulver zum Einnehmen',
  RED: 'Retard-Dragees',
  REK: 'Retard-Kapseln',
  RET: 'Retard-Tabletten',
  RGR: 'Retard-Granulat',
  RKA: 'Rektal-Kapseln',
  RMS: 'Retard-Mikrokapseln und Suspensionsmittel',
  RSC: 'Rektalschaum',
  RSU: 'Rektalsuspension',
  RUT: 'Retard-überzogene Tabletten',
  SAF: 'Saft',
  SAL: 'Salbe',
  SAM: 'Salbe zur Anwendung in der Mundhöhle',
  SCH: 'Schaum',
  SEI: 'Seife',
  SHA: 'Shampoo',
  SIR: 'Sirup',
  SLZ: 'Salz',
  SMF: 'Schmelzfilm',
  SMT: 'Schmelztabletten',
  SMU: 'Suppositorien mit Mulleinlage',
  SPA: 'Sprühpflaster',
  SPF: 'Spritzampullen ohne Kanüle',
  SPL: 'Spüllösung',
  SPR: 'Spray',
  SRI: 'Spritzen',
  SSU: 'Säuglings-Suppositorien',
  STA: 'Stechampullen',
  STB: 'Stäbchen',
  STI: 'Stifte',
  STR: 'Streifen',
  SUB: 'Substanz',
  SUE: 'Suspension zum Einnehmen',
  SUL: 'Sublingualtabletten',
  SUP: 'Suppositorien',
  SUS: 'Suspension',
  SUT: 'Subkutane Tabletten',
  SUV: 'Suspension für einen Vernebler',
  SWA: 'Schwämme',
  TAB: 'Tabletten',
  TAE: 'Täfelchen',
  TAM: 'Tампонaden',
  TEE: 'Tee',
  TEI: 'Teig',
  TES: 'Test',
  TIN: 'Tinktur',
  TKA: 'Tabletten in Kalenderpackung',
  TLE: 'Tabletten zur Herstellung einer Lösung zum Einnehmen',
  TMR: 'Tabletten magensaftresistent',
  TON: 'Tonikum',
  TPN: 'Tampon',
  TPO: 'Tamponade',
  TRA: 'Trinkampullen',
  TRI: 'Trituration',
  TRO: 'Tropfen',
  TRS: 'Trockensubstanz mit Lösungsmittel',
  TSA: 'Trockensaft',
  TSE: 'Tabletten zur Herstellung einer Suspension zum Einnehmen für ein Dosierspender',
  TSS: 'Trockensubstanz ohne Lösungsmittel',
  TST: 'Teststäbchen',
  TSY: 'Transdermales System',
  TTR: 'Trinktabletten',
  TUB: 'Tube',
  TUE: 'Tücher',
  TUP: 'Tupfer',
  TVW: 'Tablette mit veränderter Wirkstofffreisetzung',
  UTA: 'Überzogene Tabletten',
  VAL: 'Vaginallösung',
  VAR: 'Vaginalring',
  VCR: 'Vaginalcreme',
  VER: 'Verband',
  VGE: 'Vaginalgel',
  VKA: 'Vaginal-Kapseln',
  VLI: 'Vlies',
  VOV: 'Vaginal-Ovula',
  VST: 'Vaginal-Suppositorien',
  VTA: 'Vaginaltabletten',
  WAT: 'Watte',
  WGA: 'Wundgaze',
  WKA: 'Weichkapseln',
  WKM: 'Weichkapseln magensaftresistent',
  WSY: 'Wirkstoffhaltiges System',
  XDG: 'Duschgel',
  XDS: 'Deo-Spray',
  XFE: 'Festiger',
  XGM: 'Gesichtsmaske',
  XHA: 'Haarspülung',
  XHS: 'Haarshampoo',
  XNC: 'Nachtcreme',
  XPK: 'Körperpflege',
  XTC: 'Tagescreme',
  ZAM: 'Zylinderampullen',
  ZBU: 'Zahnbürste',
  ZCR: 'Zahncreme',
  ZGE: 'Zahngel',
  ZKA: 'Zerbeiß-Kapseln',
  ZPA: 'Zahnpasta',
};

/** Allowed fraction strings in structured dosage fields. */
export const ALLOWED_FRACTIONS = [
  '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10',
  '1/2', '1/3', '1/4', '2/3', '3/4',
] as const;

/** Get the display label for a section, falling back to freeTitle or code. */
export function getSectionLabel(section: { code?: string; freeTitle?: string }): string {
  if (section.code && SECTION_LABELS[section.code]) {
    return SECTION_LABELS[section.code];
  }
  return section.freeTitle ?? section.code ?? 'Medikation';
}
